scanner.o : main.cpp interpreter.cpp binaryTree.cpp scanner.h binaryTree.h interpreter.h common.h
	g++ -c interpreter.cpp 
	g++ -c binaryTree.cpp
	g++ -c main.cpp
	g++ interpreter.o binaryTree.o main.o -o main
