scanner.o : main.cpp staticChecker.cpp binaryTree.cpp scanner.h binaryTree.h staticChecker.h common.h emptyListChecker.cpp emptyListChecker.h
	g++ -c staticChecker.cpp
	g++ -c emptyListChecker.cpp 
	g++ -c binaryTree.cpp
	g++ -c main.cpp
	g++ staticChecker.o emptyListChecker.o binaryTree.o main.o -o main
